# Global vatiable settings
X_LIMIT = 100
Y_LIMIT = 100
INFECTION_DAYS = 15
MORTALITY_RATE = 10
WALK_DAYS = 500
NODES = 200
#PATTERN = 'random'
PATTERN = 'linear'
LEAVE_TRACE = False
VISUALIZATION = True